/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d653d155-21b9-4a4c-bec0-a4dc367ead3f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_utXEL1epC",
    "aws_user_pools_web_client_id": "55nhe8agau3vbji2b8j6jroq8n",
    "oauth": {},
    "predictions": {
        "identify": {
            "identifyText": {
                "proxy": false,
                "region": "us-east-1",
                "defaults": {
                    "format": "ALL"
                }
            }
        },
        "convert": {
            "translateText": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "sourceLanguage": "id",
                    "targetLanguage": "en"
                }
            }
        }
    }
};


export default awsmobile;
